package wui.bridge;

/**
	The entry point WinUI calls to start the Haxe runtime.

	`wui` used to be a pure transpiler: the generated project linked no hxcpp, so
	no Haxe ran in a built app. It does now — this class is what boots it, and
	what native code calls back into.

	## How the boot works

	WinUI owns the entry point (`wWinMain`, via `App`), so Haxe cannot own `main`.
	The pattern is the one both sibling backends already use:

	- **`qui`**: Qt owns `main` and calls `hx::Init()` *after* the view exists.
	- **`sui`**: Swift owns `@main` and calls `haxe_bridge_init` through `dlsym`,
	  so the runtime stays optional and detected.

	Here, `App::OnLaunched` calls `wui_bridge_init()` before building the window.
	The call is emitted by the generator, so an app gets it without asking.

	## The two mains

	hxcpp emits a `__main__` translation unit whose `main()` would clash with the
	one WinUI provides. Building with **`-D static_link`** replaces it with
	`__lib__`, which exposes `__hxcpp_lib_main()` and declares no `main` at all —
	hxcpp's own answer to being embedded, and it runs `lib.exe` itself to produce
	the static library.

	## Status

	**W1, W2 and W3 done, all verified on Windows by clicking.** MSVC links the
	hxcpp library, `OnLaunched` boots it, a button whose action is a Haxe closure
	runs that closure, and a Haxe write to `@:state` reaches the controls.

	Both directions therefore work: C++ -> Haxe through `wui_bridge_invoke`,
	Haxe -> C++ through `wui_bridge_push_int`.

	What is left: the generator still translates `StateAction`s into C++ that
	mutates `s_<name>` behind Haxe's back — so both paths hold a value and they
	drift if mixed — and it still guesses an action from a button's label when
	none is given. W4 removes both. See `wui-hxcpp.md` in the atelier repo.
**/
#if cpp
@:cppFileCode('
#include <hxcpp.h>

// Generated by hxcpp into __lib__.cpp when compiling with -D static_link.
// It sets the stack top, runs hx::Boot() and then __boot_all(), which is what
// actually initialises every Haxe class. hx::Init() alone starts the runtime
// but boots nothing, so the first call into Haxe would find empty statics.
extern "C" void __hxcpp_lib_main();

static bool s_wui_haxe_started = false;

// Called by App::OnLaunched before the window is built.
//
// Idempotent: WinUI can raise OnLaunched more than once (relaunch, activation),
// and booting the runtime twice would be fatal.
extern "C" void wui_bridge_init() {
    if (s_wui_haxe_started) return;
    s_wui_haxe_started = true;
    __hxcpp_lib_main();

    // Cross back into Haxe immediately. Booting proves the library linked;
    // only a call landing in Haxe code proves the runtime is usable, so W1
    // is not done until this line reports for itself.
    ::wui::bridge::HaxeBridge_obj::hello();
}

// Whether the runtime is up. Lets generated code degrade rather than crash if
// the library was not linked in.
extern "C" bool wui_bridge_ready() {
    return s_wui_haxe_started;
}

// Build the Haxe view tree once and collect its closures into the registry.
//
// The class name is passed as a string because the generator writes App.cpp and
// already knows it -- which saves defining a Haxe type from the macro just to
// carry one identifier.
extern "C" int wui_bridge_install(const char* appClass) {
    if (!s_wui_haxe_started) return 0;
    return ::wui::bridge::HaxeBridge_obj::install(::String(appClass));
}

// Run the Haxe closure registered under `id`. Called from a Click handler, on
// the UI thread.
extern "C" void wui_bridge_invoke(int id) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invoke(id);
}

// ---- Haxe state -> generated C++ ----
//
// A slot, not a symbol resolved at link time. The generated MainWindow.cpp owns
// `s_<name>` and `notify_<name>()`, so it registers a handler here at startup and
// this library never names it. That keeps the hxcpp library linkable on its own:
// a test binary links it with no handler and pushes nowhere, which is how `sui`
// keeps its runtime optional and detected.
typedef void (*wui_int_handler)(const char*, int);
static wui_int_handler s_wui_int_handler = nullptr;

extern "C" void wui_bridge_set_int_handler(wui_int_handler fn) {
    s_wui_int_handler = fn;
}

// Called from Haxe when a state changes. Getting onto the UI thread is the
// handler\'s business -- it is the side that knows about the dispatcher.
extern "C" void wui_bridge_push_int(const char* name, int value) {
    if (s_wui_int_handler) s_wui_int_handler(name, value);
}
')
#end
@:keep
class HaxeBridge {
	/**
		Proof of life, called from Haxe once the runtime is up.

		W1 succeeds when this line appears in the debug output of a running WinUI
		app — it means MSVC linked the hxcpp library, WinUI called into it, and
		Haxe executed. Nothing else about the app changes yet.
	**/
	public static function hello():Void {
		trace("[wui] Haxe runtime started");
	}

	/**
		Build the app's view tree in Haxe and register the closures it carries.

		The generated C++ builds the *controls*; this builds the same tree on the
		Haxe side purely to reach the closures, which exist nowhere else. `body()`
		is compiled like any other method even though the generated app never
		calls it — the macro reads it at compile time, and here we run it.

		Returns how many closures were found, so the caller can tell an app with
		no Haxe actions from a walk that went wrong.
	**/
	public static function install(appClass:String):Int {
		Callbacks.reset();

		var cls = Type.resolveClass(appClass);
		if (cls == null) {
			trace('[wui] install: class $appClass not found');
			return 0;
		}

		var app:Dynamic = Type.createInstance(cls, []);
		if (app == null) {
			trace('[wui] install: could not instantiate $appClass');
			return 0;
		}

		var root:View = app.body();
		if (root == null) {
			trace('[wui] install: $appClass.body() returned null');
			return 0;
		}

		collect(root);
		bindStates();
		return Callbacks.count();
	}

	/**
		Make every `@:state` field push its writes to the generated C++.

		Constructing the app filled `wui.state.State`'s registry, so the fields
		are already there to be found — no macro-generated glue needed to name
		them. Each one gets a subscriber that forwards to the native handler, and
		since `wui.state.State` already routes its platform sink through that
		subscriber list, a plain `count.value = 3` reaches the UI.

		**Only `Int` travels today.** The other types are reported rather than
		skipped in silence: a state that quietly stops updating the UI is the
		failure this whole increment exists to make impossible.
	**/
	static function bindStates():Int {
		var bound = 0;

		for (name in wui.state.State._registry.keys()) {
			var st:Dynamic = wui.state.State._registry.get(name);
			if (st == null) continue;

			var current:Dynamic = st.peek();
			if (Std.isOfType(current, Int)) {
				st.subscribe(function(v:Dynamic) {
					pushInt(name, cast(v, Int));
				});
				bound++;
			} else {
				trace('[wui] state "$name": only Int reaches the UI so far, not pushing');
			}
		}

		return bound;
	}

	/** Hand one integer to the generated C++, which owns `s_<name>`. **/
	static function pushInt(name:String, value:Int):Void {
		#if cpp
		untyped __cpp__("wui_bridge_push_int({0}.utf8_str(), {1})", name, value);
		#end
	}

	/**
		Depth-first over `children`, registering each button that carries a Haxe
		closure.

		**The order is the contract.** The generator numbers the same tree with
		the same walk, so anything that changes this traversal changes which
		closure a click runs — see `Callbacks`.
	**/
	static function collect(view:View):Void {
		if (view == null) return;

		if (view.viewType == "Button") {
			// Exactly one registration per button that has an action, in either
			// form, because the generator numbers buttons the same way. A button
			// carrying both takes the closure: it is the more specific of the two.
			var cb = view.properties.get("onClick");
			var action = view.properties.get("action");

			if (Reflect.isFunction(cb)) {
				Callbacks.register(cb);
			} else if (action != null) {
				Callbacks.register(function() Actions.run(action));
			}
		}

		for (child in view.children) collect(child);
	}

	/** Is the native side up? False when the library was not linked. **/
	public static function isReady():Bool {
		#if cpp
		var ready:Bool = false;
		untyped __cpp__("{0} = wui_bridge_ready()", ready);
		return ready;
		#else
		return false;
		#end
	}
}
