package wui.bridge;

/**
	The entry point WinUI calls to start the Haxe runtime.

	`wui` is currently a transpiler: the generated Visual Studio project links no
	hxcpp, so no Haxe runs in a built app. This class is the first step out of
	that — increment **W1** of the `wui`-on-hxcpp chantier.

	## How the boot works

	WinUI owns the entry point (`wWinMain`, via `App`), so Haxe cannot own `main`.
	The pattern is the one both sibling backends already use:

	- **`qui`**: Qt owns `main` and calls `hx::Init()` *after* the view exists.
	- **`sui`**: Swift owns `@main` and calls `haxe_bridge_init` through `dlsym`,
	  so the runtime stays optional and detected.

	Here, `App::OnLaunched` calls `wui_bridge_init()` before building the window.
	The call is emitted by the generator, so an app gets it without asking.

	## The two mains

	hxcpp emits a `__main__` translation unit whose `main()` would clash with the
	one WinUI provides. Building with **`-D static_link`** replaces it with
	`__lib__`, which exposes `__hxcpp_lib_main()` and declares no `main` at all —
	hxcpp's own answer to being embedded, and it runs `lib.exe` itself to produce
	the static library.

	## Status

	**W1 done, verified on Windows.** MSVC links the hxcpp library into the
	WinUI app, `OnLaunched` calls in, Haxe executes, and the window runs.

	What this does *not* mean: the app's buttons are still driven by C++ the
	generator emitted, not by the runtime. Booting Haxe and letting Haxe drive
	the UI are different steps -- see `wui-hxcpp.md` in the atelier repo for the
	sequence and what each increment proves.
**/
#if cpp
@:cppFileCode('
#include <hxcpp.h>

// Generated by hxcpp into __lib__.cpp when compiling with -D static_link.
// It sets the stack top, runs hx::Boot() and then __boot_all(), which is what
// actually initialises every Haxe class. hx::Init() alone starts the runtime
// but boots nothing, so the first call into Haxe would find empty statics.
extern "C" void __hxcpp_lib_main();

static bool s_wui_haxe_started = false;

// Called by App::OnLaunched before the window is built.
//
// Idempotent: WinUI can raise OnLaunched more than once (relaunch, activation),
// and booting the runtime twice would be fatal.
extern "C" void wui_bridge_init() {
    if (s_wui_haxe_started) return;
    s_wui_haxe_started = true;
    __hxcpp_lib_main();

    // Cross back into Haxe immediately. Booting proves the library linked;
    // only a call landing in Haxe code proves the runtime is usable, so W1
    // is not done until this line reports for itself.
    ::wui::bridge::HaxeBridge_obj::hello();
}

// Whether the runtime is up. Lets generated code degrade rather than crash if
// the library was not linked in.
extern "C" bool wui_bridge_ready() {
    return s_wui_haxe_started;
}
')
#end
@:keep
class HaxeBridge {
	/**
		Proof of life, called from Haxe once the runtime is up.

		W1 succeeds when this line appears in the debug output of a running WinUI
		app — it means MSVC linked the hxcpp library, WinUI called into it, and
		Haxe executed. Nothing else about the app changes yet.
	**/
	public static function hello():Void {
		trace("[wui] Haxe runtime started");
	}

	/** Is the native side up? False when the library was not linked. **/
	public static function isReady():Bool {
		#if cpp
		var ready:Bool = false;
		untyped __cpp__("{0} = wui_bridge_ready()", ready);
		return ready;
		#else
		return false;
		#end
	}
}
